schema_version = "1.0.0"

id = "stormworks_mesh_io"
version = "1.0.0"
name = "Stormworks Mesh IO"
tagline = "Import/export Stormworks mesh"
maintainer = "Teinishi"
type = "add-on"

website = "https://github.com/Teinishi/blender_stormworks_mesh"

tags = ["Import-Export", "Mesh"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export Stormworks mesh and physics mesh from/to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/"
]
